POST http://127.0.0.1:5000/users/
Accept: application/json
Content-Type: application/json

{
  "username": "ivan",
  "password": "P@ssw0rd",
  "role": "user"
}

###

POST http://127.0.0.1:5000/auth/
Accept: application/json
Content-Type: application/json

{
  "username": "ivan",
  "password": "P@ssw0rd"
}

###

PUT http://127.0.0.1:5000/auth/
Accept: application/json
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcwODcwMDAwNn0.4m6QyN_fRE65K3hgEuJvHfLSSdhJ_HZzXZw0630n41Y"
}

###

GET http://127.0.0.1:5000/movies/
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y

###

GET http://127.0.0.1:5000/movies/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y

###

GET http://127.0.0.1:5000/movies/?genre_id=4
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y

###

GET http://127.0.0.1:5000/movies/?year=1980
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y

###

GET http://127.0.0.1:5000/directors/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y

###

GET http://127.0.0.1:5000/directors/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y

###

GET http://127.0.0.1:5000/genres/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y

###

GET http://127.0.0.1:5000/genres/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y

###

GET http://127.0.0.1:5000/movies/21
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y

###

POST http://127.0.0.1:5000/movies/
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y

{
  "title": "Гарри Поттер мой кумир!",
  "trailer": "таким фильмам не нужны трейлеры",
  "year": 1990,
  "rating": 10,
  "description": "10 из 10!"
}

###

PUT http://127.0.0.1:5000/movies/21
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

DELETE http://127.0.0.1:5000/movies/21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTg3MTQ5Mn0.ErHj77kylKtO0y0fQxTN5elv40nvPg2B3p3z2qfP-0Y